#!/usr/bin/perl -s

my $Remove = $r;

use strict;

chdir 'ionosphere' or die "Could not cd into ionsophere/\n";
my @files = glob('*_b1.*');

my $file1;   # _b1 file
my $file2;   # _b2 file
my $fileout; # concatenated file
my $err;     # error message from cat

foreach $file1 (sort @files){
    $file2 = $file1;
    $file2 =~ s/b1/b2/;
    $fileout = $file1;
    $fileout =~ s/_b1//;
    print "cat $file1 $file2 > $fileout\n";
    $err = `cat $file1 $file2 > $fileout`;
    die "Error occured: $err\n" if $err;
    unlink($file1, $file2) if $Remove;
}
