#^CFG FILE TESTING

### TESTS FOR THE STAND-ALONE GITM ###

TIMINGFILE =./.test_file_timing.txt
STARTTIME  =rm $(TIMINGFILE); date +%s |xargs printf >$(TIMINGFILE);printf "*-1+">>$(TIMINGFILE);
ENDTIME   = date +%s >>$(TIMINGFILE); cat $(TIMINGFILE) | bc;

timing:
	-@if([ "${TIMING}" ]); then $(STARTTIME) fi
	-@if([ "${TIMING}" ]); then $(ENDTIME) fi

test: 
	@rm -f *.diff
	-@($(MAKE) test_earth)
	-@($(MAKE) test_mars)
	@ls -l *.diff

# All tests are done in this directory:
TESTDIR = run_test

# Reference solution is put into this directory when needed:
REFDIR = run_test_ref

test_help:
	@echo "    test                       (run all tests with ${MPIRUN})"
	@echo "    test KEEP=y                (run tests and keep run directories)"
	@echo "    test MPIRUN=               (run tests serially)"
	@echo "    test NPFLAG=-n NP=3        (run tests with ${PARALLEL} -n 3)"
	@echo "    test PARALLEL='mpiexec'    (run tests with mpiexec)"
	@echo "    test_earth                 (run Earth GITM test)"
	@echo "    test_mars                  (run Mars GITM test)"

test_rundir:
	rm -rf ${TESTDIR}
	$(MAKE) rundir RUNDIR=${TESTDIR} STANDALONE=YES GMDIR=`pwd`

### EARTH GITM TEST ###

test_earth:
	@echo "test_earth_1d..." > test_earth.diff
	$(MAKE) test_earth_1d
	@echo "test_earth_eclipse..." >> test_earth.diff
	$(MAKE) test_earth_eclipse
	@echo "test_earth_3d..." >> test_earth.diff
	$(MAKE) test_earth_3d

test_earth_1d:
	@echo "test_earth_1d_compile..." > test_1d.diff
	$(MAKE) test_earth_1d_compile
	@echo "test_earth_1d_rundir..." >> test_1d.diff
	$(MAKE) test_earth_1d_rundir
	@echo "test_earth_1d_run..." >> test_1d.diff
	$(MAKE) test_earth_1d_run
	@echo "test_earth_1d_check..." >> test_1d.diff
	$(MAKE) test_earth_1d_check
	@if([ "${KEEP}" ]); then rm -rf run_$@; mv ${TESTDIR} run_$@; fi

test_earth_eclipse:
	@echo "test_earth_eclipse_compile..." > test_eclipse.diff
	$(MAKE) test_earth_eclipse_compile
	@echo "test_earth_eclipse_rundir..." >> test_eclipse.diff
	$(MAKE) test_earth_eclipse_rundir
	@echo "test_earth_eclipse_run..." >> test_eclipse.diff
	$(MAKE) test_earth_eclipse_run
	@echo "test_earth_eclipse_check..." >> test_eclipse.diff
	$(MAKE) test_earth_eclipse_check
	@if([ "${KEEP}" ]); then rm -rf run_$@; mv ${TESTDIR} run_$@; fi

test_earth_3d:
	@echo "test_earth_3d_compile..." > test_3d.diff
	$(MAKE) test_earth_3d_compile
	@echo "test_earth_3d_rundir..." >> test_3d.diff
	$(MAKE) test_earth_3d_rundir
	@echo "test_earth_3d_run..." >> test_3d.diff
	$(MAKE) test_earth_3d_run
	@echo "test_earth_3d_check..." >> test_3d.diff
	$(MAKE) test_earth_3d_check
	@if([ "${KEEP}" ]); then rm -rf run_$@; mv ${TESTDIR} run_$@; fi

# ----------------------------------------------------
# 1D tests
# ----------------------------------------------------

# Plain 1D
test_earth_1d_compile:
	./Config.pl -Earth -g=1,1,50,4
	$(MAKE) GITM

test_earth_1d_rundir:
	rm -rf ${TESTDIR}
	$(MAKE) rundir RUNDIR=${TESTDIR}

test_earth_1d_run:
	cd ${TESTDIR}; cp ./DataIn/UAM.in.1d ./UAM.in
	cd ${TESTDIR}; ${MPIRUN} -np 1 ./GITM.exe > runlog_earth_1d

test_earth_1d_check:
	@(${SCRIPTDIR}/DiffNum.pl -b -r=1e-5 \
		${TESTDIR}/UA/data/log0000000?.dat ${TESTDIR}/UA/DataIn/log00000004.1d.dat \
		> test_earth_1d.diff)
	ls -l test_earth_1d.diff

# Eclipse 1D
test_earth_eclipse_compile:
	./Config.pl -Earth -g=1,1,50,4
	$(MAKE) GITM

test_earth_eclipse_rundir:
	rm -rf ${TESTDIR}
	$(MAKE) rundir RUNDIR=${TESTDIR}

test_earth_eclipse_run:
	cd ${TESTDIR}; cp ./DataIn/UAM.in.eclipse ./UAM.in
	cd ${TESTDIR}; ${MPIRUN} -np 1 ./GITM.exe > runlog_earth_eclipse

test_earth_eclipse_check:
	@(${SCRIPTDIR}/DiffNum.pl -b -r=1e-5 \
		${TESTDIR}/UA/data/log0000000?.dat ${TESTDIR}/UA/DataIn/log00000002.eclipse.dat \
		> test_earth_eclipse.diff)
	ls -l test_earth_eclipse.diff

# ----------------------------------------------------
# 3D tests
# ----------------------------------------------------

test_earth_3d_compile:
	./Config.pl -Earth -g=9,9,50,4
	$(MAKE) GITM

test_earth_3d_rundir:
	rm -rf ${TESTDIR}
	$(MAKE) rundir RUNDIR=${TESTDIR}

test_earth_3d_run:
	cd ${TESTDIR}; cp ./DataIn/UAM.in.3d ./UAM.in
	cd ${TESTDIR}; ${MPIRUN} -np 4 ./GITM.exe

test_earth_3d_check:
	(${SCRIPTDIR}/DiffNum.pl -b -r=1e-5 \
		${TESTDIR}/UA/data/log00000002.dat ${TESTDIR}/UA/DataIn/log00000002.3d.dat \
		> test_earth_3d.diff)
	ls -l test_earth_3d.diff

### MARS GITM TEST ###

test_mars:
	@echo "test_mars_1d..." > test_mars.diff
	make test_mars_1d
	@echo "test_mars_3d..." >> test_mars.diff
	make test_mars_3d

test_mars_1d:
	@echo "test_mars_1d_compile..." > test_1d.diff
	$(MAKE) test_mars_1d_compile
	@echo "test_mars_1d_rundir..." >> test_1d.diff
	$(MAKE) test_mars_1d_rundir
	@echo "test_mars_1d_run..." >> test_1d.diff
	$(MAKE) test_mars_1d_run
	@echo "test_mars_1d_check..." >> test_1d.diff
	$(MAKE) test_mars_1d_check
	@if([ "${KEEP}" ]); then rm -rf run_$@; mv ${TESTDIR} run_$@; fi

test_mars_3d:
	@echo "test_mars_3d_compile..." > test_3d.diff
	$(MAKE) test_mars_3d_compile
	@echo "test_mars_3d_rundir..." >> test_3d.diff
	$(MAKE) test_mars_3d_rundir
	@echo "test_mars_3d_run..." >> test_3d.diff
	$(MAKE) test_mars_3d_run
	@echo "test_mars_3d_check..." >> test_3d.diff
	$(MAKE) test_mars_3d_check
	@if([ "${KEEP}" ]); then rm -rf run_$@; mv ${TESTDIR} run_$@; fi

# ----------------------------------------------------
# 1D tests
# ----------------------------------------------------

test_mars_1d_compile:
	./Config.pl -Mars -g=1,1,120,4
	$(MAKE) GITM

test_mars_1d_rundir:
	rm -rf ${TESTDIR}
	$(MAKE) rundir RUNDIR=${TESTDIR}

test_mars_1d_run:
	cd ${TESTDIR}; cp ./DataIn/UAM.mars.in.1d ./UAM.in
	cd ${TESTDIR}; ${MPIRUN} ./GITM.exe > runlog_mars_1d

test_mars_1d_check:
	@(${SCRIPTDIR}/DiffNum.pl -b -r=1e-5 \
		${TESTDIR}/UA/data/log0000000?.dat ${TESTDIR}/UA/DataIn/log00000002.1d.dat.mars \
		> test_mars_1d.diff)
	ls -l test_mars_1d.diff

# ----------------------------------------------------
# 3D tests
# ----------------------------------------------------

test_mars_3d_compile:
	./Config.pl -Mars -g=8,4,120,4
	$(MAKE) GITM

test_mars_3d_rundir:
	rm -rf ${TESTDIR}
	$(MAKE) rundir RUNDIR=${TESTDIR}

test_mars_3d_run:
	cd ${TESTDIR}; cp ./DataIn/UAM.mars.in.3d ./UAM.in
	cd ${TESTDIR}; ${MPIRUN} -np 4 ./GITM.exe > runlog_mars_3d

test_mars_3d_check:
	(${SCRIPTDIR}/DiffNum.pl -b -r=1e-5 \
		${TESTDIR}/UA/data/log0000000?.dat ${TESTDIR}/UA/DataIn/log00000002.3d.dat.mars \
		> test_mars_3d.diff)
	ls -l test_mars_3d.diff

