#BOP
#!ROUTINE: CON/Makefile.def - original file for Makefile.def
#!DESCRIPTION:
# This file is copied into the main directory as Makefile.def during installation.
# The copied file contains variables that define the operating system (OS), 
# the main directory (SWMF\_ROOT). The version variables (XY\_VERSION)
# are modified to select the appropriate component and module versions.
# Normally this is done with the Config.pl script.
# The Makefile.def file is included in almost all Makefile-s in the SWMF and its components.
#EOP

#BOC

# This file is needed in dependency rules of component libraries:
MAKEFILE_COMP_SELECT = ${DIR}/Makefile.def

# If this Makefile is used the components are not in a stand alone mode
STANDALONE=NO

# Do not touch the lines above this line #####################################
#
# Select the physics components by commenting out exactly one version for each
# This is normally done by the perl script Config.pl

GM_VERSION = Empty#			^CMP IF GM
IE_VERSION = Empty#			^CMP IF IE
IH_VERSION = Empty#			^CMP IF IH
IM_VERSION = Empty#			^CMP IF IM
LA_VERSION = Empty#			^CMP IF LA
OH_VERSION = Empty#			^CMP IF OH
PS_VERSION = Empty#			^CMP IF PS
PW_VERSION = Empty#			^CMP IF PW
RB_VERSION = Empty#			^CMP IF RB
SC_VERSION = Empty#			^CMP IF SC
SP_VERSION = Empty#			^CMP IF SP
UA_VERSION = Empty#			^CMP IF UA

TIMING_VERSION = TIMING/src
#TIMING_VERSION = TIMING/srcEmpty

INT_VERSION = Interface
#INT_VERSION = Stubs

# Do not touch anything below this line #####################################

#
# Control, Coupler, Interface
#

CONDIR       = ${DIR}/CON
CONTROLDIR   = ${CONDIR}/Control/src
LIBRARYDIR   = ${CONDIR}/Library/src
COUPLERDIR   = ${CONDIR}/Coupler/src
INTERFACEDIR = ${CONDIR}/${INT_VERSION}/src

#
# Component directories
#

GMDIR = ${DIR}/GM/${GM_VERSION}#	^CMP IF GM
IEDIR = ${DIR}/IE/${IE_VERSION}#	^CMP IF IE
IHDIR = ${DIR}/IH/${IH_VERSION}#	^CMP IF IH
IMDIR = ${DIR}/IM/${IM_VERSION}#	^CMP IF IM
LADIR = ${DIR}/LA/${LA_VERSION}#	^CMP IF LA
OHDIR = ${DIR}/OH/${OH_VERSION}#	^CMP IF OH
PSDIR = ${DIR}/PS/${PS_VERSION}#	^CMP IF PS
PWDIR = ${DIR}/PW/${PW_VERSION}#	^CMP IF PW
RBDIR = ${DIR}/RB/${RB_VERSION}#	^CMP IF RB
SCDIR = ${DIR}/SC/${SC_VERSION}#	^CMP IF SC
SPDIR = ${DIR}/SP/${SP_VERSION}#	^CMP IF SP
UADIR = ${DIR}/UA/${UA_VERSION}#	^CMP IF UA

#
# Utilities
#

UTILDIR            = ${DIR}/util
TIMINGDIR          = ${UTILDIR}/${TIMING_VERSION}
NOMPIDIR           = ${UTILDIR}/NOMPI/src
DATAREADINDICESDIR = ${UTILDIR}/DATAREAD/srcIndices
MAGNETOGRAMDIR     = ${UTILDIR}/DATAREAD/srcMagnetogram
EMPIRICALEEDIR     = ${UTILDIR}/EMPIRICAL/srcEE
EMPIRICALIEDIR     = ${UTILDIR}/EMPIRICAL/srcIE
EMPIRICALGMDIR     = ${UTILDIR}/EMPIRICAL/srcGM
EMPIRICALUADIR     = ${UTILDIR}/EMPIRICAL/srcUA

#
# Shared things
#

COMMONDIR = ${DIR}/share
SCRIPTDIR = ${COMMONDIR}/Scripts
SHAREDIR  = ${COMMONDIR}/Library/src
INCLDIR   = ${COMMONDIR}/include
BUILDDIR  = ${COMMONDIR}/build

#
# Binaries, libraries, and runs
#

BINDIR    = ${DIR}/bin
LIBDIR    = ${DIR}/lib
RUNDIR    = ${DIR}/run

#
# This ensures that typing make without arguments does not cause much harm
#
localdefault: help
#EOC
