INSTALL_FILES = \
	Control/src/Makefile.DEPEND \
	Library/src/Makefile.DEPEND \
	Coupler/src/Makefile.DEPEND \
	Interface/src/Makefile.DEPEND \
	Stubs/src/Makefile.DEPEND

install:
	touch ${INSTALL_FILES}

distclean:
	rm -f ${INSTALL_FILES} *~
