# Local Makefile.def

localdefault: help # default target

DIR     = ${MYDIR}

SCRIPTDIR = ${MYDIR}/share/Scripts
LIBDIR    = ${MYDIR}/src
RUNDIR    = ${MYDIR}/run
BINDIR    = ${MYDIR}/src
INCLDIR   = ${MYDIR}/share/include
SHAREDIR  = ${MYDIR}/share/Library/src
NOMPIDIR  = ${MYDIR}/util/NOMPI/src
EMPIRICALIEDIR     = ${MYDIR}/util/EMPIRICAL/srcIE
EMPIRICALUADIR     = ${MYDIR}/util/EMPIRICAL/srcUA
DATAREADINDICESDIR = ${MYDIR}/util/DATAREAD/srcIndices

