# Local Makefile.def

localdefault: help # default target

DIR     = ${UADIR}

SCRIPTDIR = ${UADIR}/share/Scripts
LIBDIR    = ${UADIR}/src
RUNDIR    = ${UADIR}/run
BINDIR    = ${UADIR}/src
SHAREDIR  = ${UADIR}/share/Library/src
EMPIRICALIEDIR     = ${UADIR}/util/EMPIRICAL/srcIE
DATAREADINDICESDIR = ${UADIR}/util/DATAREAD/srcIndices

