#!/bin/csh

echo ' '
echo ' Converting .ps files to .jpg'
echo ' '

set dir = .
foreach i (*.ps)
  set f = `basename $i .ps`
  echo '  working on '${f}' ...'
  gs -sDEVICE=jpeg -sOutputFile=${f}_tmp.jpg -dNOPAUSE -q -dBATCH $i
  convert -crop 0x0 -rotate 90 ${f}_tmp.jpg ${f}.jpg
  /bin/rm -f ${f}_tmp.jpg
end

