#!/bin/csh

echo ' '
echo ' Converting .ps files to .png'
echo ' '

set dir = .
foreach i (*.ps)
  set f = `basename $i .ps`
  echo '  working on '${f}' ...'
  gs -sDEVICE=png256 -sOutputFile=${f}_tmp.png -dNOPAUSE -q -dBATCH $i
#  convert -crop 0x0 ${f}_tmp.png ${f}.png
  convert -crop 0x0 -rotate 90 ${f}_tmp.png ${f}.png
  /bin/rm -f ${f}_tmp.png
end

