#!/bin/csh

if( "$1" == "")then
  echo ' '
  echo ' USAGE: tpBatchLC 3dfile'
  echo '   NOTE: .plt will be added to 3dfile name.'
  exit
endif

echo 'Starting Tecplot batch for slices ...'
tecplot10 -b -p batchExtractLC2.mcr ${1}.plt

echo 'Starting Tecplot batch for B lines ...'
tecplot10 -b -p batchExtractLC.mcr ${1}.plt

echo 'Starting IDL batch ...'
echo '.r line2rodVRML.pro' > .idlinput
echo 'tpBatch_LastClosed.dat' >> .idlinput
echo 'yes' >> .idlinput
echo '0.01' >> .idlinput
idl < .idlinput
mv tmp.dat tpBatch_LastClosedROD.dat
preplot tpBatch_LastClosedROD.dat
rm -f tmpP tmpX tpBatch_LastClosedROD.dat

echo 'Created tpBatch_LastClosed.dat and tpBatch_LastClosedROD.plt'

#./ps2jpg
./ps2png
rm -f *.ps

mkdir $1
mv Slice* ${1}/.
mv *wrl ${1}/.
cp README ${1}/.

tar -czf ../${1}.tgz $1
