#^CMP COPYRIGHT UM
#^CMP FILE TESTING

TESTDIR = ${DIR}/run_test

MPIRUN = mpirun -np 2

test_help:
	@echo "    test                       (run all tests with ${MPIRUN})"
	@echo "    test MPIRUN=               (run all tests serially)"
	@echo "    test MPIRUN='mpirun -np 3' (run test with mpirun -np 3)"
	@echo "    test MPIRUN='mprun -np 2'  (run test with mprun -np 2)"
	@echo "    test_comp                  (run component tests only)"
	@echo "    test_pw                    (run polar wind test only)"
	@echo "    test_esmf                  (run ESMF_SWMF test only)"

test:
	-@(make test_comp)
	-@(make test_pw)
	-@(make test_esmf)
	-@(make test_check)

test_check:
	@ls -l ??/*/*.diff *.diff > test_swmf.res
	@cat test_swmf.res
	@echo '=============================================================='\
		>> test_swmf.res
	@head -100 ??/*/*.diff *.diff >> test_swmf.res
	@echo ' '
	@echo 'See test_swmf.res and test_swmf.log for more detail...'
	@echo ' '

### Component tests ###

test_comp:
	for i in `ls -d [A-Z][A-Z]/*/ | grep -v /CVS/ | grep -v /Empty/`; \
		do ( cd $$i; make test; ); done
	ls -l *.diff [A-Z][A-Z]/*/*.diff

### SWMF tests ###

#### Polarwind test ###
#
test_pw:
	@echo "starting..." > test_pw_plots.diff
	@echo "starting..." > test_pw_restart.diff
	@echo "test_pw_compile..." > test_pw.diff
	make test_pw_compile
	@echo "test_pw_rundir..." >> test_pw.diff
	make test_pw_rundir
	@echo "test_pw_run..." >> test_pw.diff
	make test_pw_run
	@echo "test_pw_check..." >> test_pw.diff
	make test_pw_check

test_pw_compile:
	SetSWMF.pl -v=Empty,PW/PWOM
	cd PW/PWOM; ./config.pl -p=Earth
	make SWMF

test_pw_rundir:
	rm -rf ${TESTDIR}
	make rundir RUNDIR=${TESTDIR}
	cp Param/PARAM.in.test.PW ${TESTDIR}/PARAM.in
	cp Param/LAYOUT.in.test.PW ${TESTDIR}/LAYOUT.in

test_pw_run:
	cd ${TESTDIR}/PW; rm -f log.out restartOUT/* plots/*
	cd ${TESTDIR}; ${MPIRUN} ./SWMF.exe > runlog

test_pw_check:
	-@(${SCRIPTDIR}/DiffNum.pl -b ${TESTDIR}/PW/log.out \
		${PWDIR}/output/Earth/log.out \
		> test_pw.diff)
	-@(${SCRIPTDIR}/DiffNum.pl -b -r=1e-10 \
		${TESTDIR}/PW/restartOUT/restart_iline0001.dat \
		${PWDIR}/output/Earth/restart_iline0001.dat \
		> test_pw_restart.diff)
	-@(${SCRIPTDIR}/DiffNum.pl -b -r=1e-8 \
		${TESTDIR}/PW/plots/plots_iline0001.out \
		${PWDIR}/output/Earth/plots_iline0001.out \
		> test_pw_plots.diff)
	ls -l test_pw*.diff

### ESMF test ###
#
#       Targets for the ESMF compatible executable
#

test_esmf:
	@echo "test_esmf_compile..." > test_esmf.diff
	make test_esmf_compile
	@echo "test_esmf_rundir..." >> test_esmf.diff
	make test_esmf_rundir
	@echo "test_esmf_run..." >> test_esmf.diff
	make test_esmf_run
	@echo "test_esmf_check..." >> test_esmf.diff
	make test_esmf_check

test_esmf_compile:
	SetSWMF.pl -v=Empty,GM/BATSRUS,IE/Ridley_serial
	make ESMF_SWMF

test_esmf_rundir:
	rm -rf ${TESTDIR};
	make rundir RUNDIR=${TESTDIR}
	cd ESMF/ESMF_SWMF; make rundir RUNDIR=${TESTDIR}
	
test_esmf_run: 
	@cd ${TESTDIR}; rm -f PET*ESMF_LogFile
	@cd ${TESTDIR}; ${MPIRUN} ESMF_SWMF.exe > runlog
	@cd ${TESTDIR}; PostProc.pl -M -o RESULTS

test_esmf_check:
	perl -ne 'print if /error/i' PET*.ESMF_LogFile > test_esmf.diff
	${SCRIPTDIR}/DiffNum.pl -b \
		${TESTDIR}/RESULTS/GM/log_n000001.log \
		ESMF/ESMF_SWMF/output/log_n000001.log \
		>> test_esmf.diff
	gunzip -c ESMF/ESMF_SWMF/output/it000321_104510_000.idl.gz \
		> ${TESTDIR}/it000321_104510_000.idl.ref
	${SCRIPTDIR}/DiffNum.pl -b -r=1e-4 \
		${TESTDIR}/RESULTS/IE/it000321_104510_000.idl \
		${TESTDIR}/it000321_104510_000.idl.ref \
		>> test_esmf.diff
	ls -l test_esmf.diff
