#^CMP COPYRIGHT UM
#^CMP FILE TESTING

TESTDIR = ${DIR}/run_test

MPIRUN = mpirun -np 2

test_help:
	@echo "    test                       (run all tests with ${MPIRUN})"
	@echo "    test MPIRUN=               (run all tests serially)"
	@echo "    test MPIRUN='mpirun -np 3' (run test with mpirun -np 3)"
	@echo "    test MPIRUN='mprun -np 2'  (run test with mprun -np 2)"
	@echo "    test_comp                  (run component tests only)"
	@echo "    test_pw                    (run PW/PWOM test only)"
	@echo "    test_rb                    (run RB/RBE test only)"
	@echo "    test_esmf                  (run ESMF_SWMF test only)"
	@echo "    test1                      (run GM-IE-PW test only )"
	@echo "    test2                      (run SC-IH test only )"
	@echo "    test3                      (run GM-IE-IM test only )"

test:
	@rm -f *.diff
	-@(make test_comp)
	-@(make test_pw)
	-@(make test_rb)
	-@(make test_esmf)
	-@(make test1)
	-@(make test2)
	-@(make test3)
	-@(make test_check)

test_check:
	@ls -l ??/*/*.diff *.diff > test_swmf.res
	@cat test_swmf.res
	@echo '=============================================================='\
		>> test_swmf.res
	@head -100 ??/*/*.diff *.diff >> test_swmf.res
	@echo ' '
	@echo 'See test_swmf.res and test_swmf.log for more detail...'
	@echo ' '
	@echo '=============================================================='\
		>> test_swmf.res
	-@cat GM/BATSRUS/test_func.speed >> test_swmf.res

### Component tests ###

test_comp:
	for i in `ls -d [A-Z][A-Z]/*/ | grep -v /CVS/ | grep -v /Empty/`; \
		do ( cd $$i; make test; ); done
	ls -l *.diff [A-Z][A-Z]/*/*.diff

### SWMF tests ###

#### Polarwind test ###
#
test_pw:
	@echo "starting..." > test_pw.diff
	@echo "test_pw_compile..." >> test_pw.diff
	make test_pw_compile
	@echo "test_pw_rundir..." >> test_pw.diff
	make test_pw_rundir
	@echo "test_pw_run..." >> test_pw.diff
	make test_pw_run
	@echo "test_pw_check..." >> test_pw.diff
	make test_pw_check

test_pw_compile:
	./Config.pl -v=Empty,PW/PWOM -o=PW:Earth
	make SWMF PIDL

test_pw_rundir:
	rm -rf ${TESTDIR}
	make rundir RUNDIR=${TESTDIR}
	cp Param/PARAM.in.test.PW ${TESTDIR}/PARAM.in
	cp Param/LAYOUT.in.test.PW ${TESTDIR}/LAYOUT.in

test_pw_run:
	cd ${TESTDIR}/PW; rm -f log.out restartOUT/* plots/*
	cd ${TESTDIR}; ${MPIRUN} ./SWMF.exe > runlog

test_pw_check:
	-@(${SCRIPTDIR}/DiffNum.pl -b -r=1e-8 \
		${TESTDIR}/PW/plots/plots_iline0001.out \
		${PWDIR}/output/Earth/plots_iline0001.out \
		> test_pw.diff)
	ls -l test_pw*.diff

#### Radiation belt model test ###
#
test_rb:
	@echo "starting..." > test_rb.diff
	@echo "test_rb_compile..." >> test_rb.diff
	make test_rb_compile
	@echo "test_rb_rundir..." >> test_rb.diff
	make test_rb_rundir
	@echo "test_rb_run..." >> test_rb.diff
	make test_rb_run
	@echo "test_rb_check..." >> test_rb.diff
	make test_rb_check

test_rb_compile:
	./Config.pl -v=Empty,RB/RBE,GM/BATSRUS
	./Config.pl -g=GM:8,8,8,770,1 -o=GM:e=Mhd,u=Default
	make SWMF PIDL

test_rb_rundir:
	rm -rf ${TESTDIR}
	make rundir RUNDIR=${TESTDIR}
	cp Param/PARAM.in.test.RB ${TESTDIR}/PARAM.in
	cp Param/LAYOUT.in.test.RB ${TESTDIR}/LAYOUT.in
	cd ${TESTDIR}/RB/; ln -s ${RBDIR}/input/2000_223* .

test_rb_run:
	cd ${TESTDIR}/RB; rm -f 2000f223_e.fls
	cd ${TESTDIR}; ${MPIRUN} ./SWMF.exe > runlog

test_rb_check:
	gunzip -c ${RBDIR}/output/2000f223_e.fls.gz \
		> ${TESTDIR}/2000f223_e.fls.ref
	${SCRIPTDIR}/DiffNum.pl -r=0.001 -a=1e-10 \
		${TESTDIR}/RB/plots/2000f223_e.fls \
		${TESTDIR}/2000f223_e.fls.ref \
		> test_rb.diff
	ls -l test_rb.diff

### Test1: PW+IE+GM ###

test1:
	@echo "test1_compile..." > test1_gm.diff
	@echo "test1_compile..." > test1_ie.diff
	@echo "test1_compile..." > test1_pw.diff
	make test1_compile
	@echo "test1_rundir..." >> test1_gm.diff
	@echo "test1_rundir..." >> test1_ie.diff
	@echo "test1_rundir..." >> test1_pw.diff
	make test1_rundir
	@echo "test1_run..." >> test1_gm.diff
	@echo "test1_run..." >> test1_ie.diff
	@echo "test1_run..." >> test1_pw.diff
	make test1_run
	@echo "test1_check..." >> test1_gm.diff
	@echo "test1_check..." >> test1_ie.diff
	@echo "test1_check..." >> test1_pw.diff
	make test1_check

test1_compile:
	./Config.pl -v=Empty,GM/BATSRUS,IE/Ridley_serial,PW/PWOM
	./Config.pl -g=GM:8,8,8,400,100 -o=GM:u=Default,e=Mhd,PW:Earth
	make SWMF PIDL

test1_rundir:
	rm -rf ${TESTDIR}
	make rundir RUNDIR=${TESTDIR}
	cp Param/PARAM.in.test.GMIEPW ${TESTDIR}/PARAM.in
	cp Param/LAYOUT.in.test.GMIEPW ${TESTDIR}/LAYOUT.in

test1_run:
	cd ${TESTDIR}/PW; rm -f log.out restartOUT/* plots/*
	cd ${TESTDIR}; ${MPIRUN} ./SWMF.exe > runlog
	cd ${TESTDIR}; ./PostProc.pl -M RESULTS

test1_check:
	-@(${SCRIPTDIR}/DiffNum.pl -b -r=1e-7 \
		${TESTDIR}/RESULTS/PW/plots_iline0001.out \
		output/test1/PW_plots_iline0001.out \
		> test1_pw.diff)
	-@(${SCRIPTDIR}/DiffNum.pl -b -r=1e-7 \
		${TESTDIR}/RESULTS/PW/plots_iline0002.out \
		output/test1/PW_plots_iline0002.out \
		>> test1_pw.diff)
	-@(${SCRIPTDIR}/DiffNum.pl -b -r=1e-7 \
		${TESTDIR}/RESULTS/PW/plots_iline0003.out \
		output/test1/PW_plots_iline0003.out \
		>> test1_pw.diff)
	-@(${SCRIPTDIR}/DiffNum.pl -b -r=1e-7 \
		${TESTDIR}/RESULTS/PW/plots_iline0004.out \
		output/test1/PW_plots_iline0004.out \
		>> test1_pw.diff)
	-@(${SCRIPTDIR}/DiffNum.pl -b -r=1e-3 -a=1e-8 \
		${TESTDIR}/RESULTS/GM/log_n000001.log \
		output/test1/GM_log_n000001.log \
		> test1_gm.diff)
	-@(${SCRIPTDIR}/DiffNum.pl -b -r=1e-6 \
		${TESTDIR}/RESULTS/IE/logIE.log \
		output/test1/IE_logIE.log \
		> test1_ie.diff)
	-@(${SCRIPTDIR}/DiffNum.pl -b -r=1e-4 -a=1e-8 \
		${TESTDIR}/RESULTS/IE/it000321_104510_000.idl \
		output/test1/IE_it000321_104510_000.idl \
		>> test1_ie.diff)
	ls -l test1*.diff

### test2: SC+IH test ###

test2:
	@echo "test2_compile..." > test2_sc.diff
	@echo "test2_compile..." > test2_ih.diff
	make test2_compile
	@echo "test2_rundir..." >> test2_sc.diff
	@echo "test2_rundir..." >> test2_ih.diff
	make test2_rundir
	@echo "test2_run..." >> test2_sc.diff
	@echo "test2_run..." >> test2_ih.diff
	make test2_run
	@echo "test2_check..." >> test2_sc.diff
	@echo "test2_check..." >> test2_ih.diff
	make test2_check

test2_compile:
	./Config.pl -v=Empty,SC/BATSRUS,IH/BATSRUS
	./Config.pl -g=SC:4,4,4,3000,IH:8,8,8,400,1
	cd SC/BATSRUS; ./Config.pl -dynamic; cd ../..
	cd IH/BATSRUS; ./Config.pl -dynamic; cd ../..
	make SWMF PIDL EARTH_TRAJ

test2_rundir:
	rm -rf ${TESTDIR}
	make rundir RUNDIR=${TESTDIR}
	cp Param/PARAM.in.test.SCIH ${TESTDIR}/PARAM.in
	cp Param/LAYOUT.in.test.SCIH ${TESTDIR}/LAYOUT.in
	cd ${TESTDIR}/IH; cp Param/EARTH_TRAJ.in .; \
		${BINDIR}/EARTH_TRAJ.exe > earth_traj.dat

test2_run:
	cd ${TESTDIR}; ${MPIRUN} ./SWMF.exe > runlog
	cd ${TESTDIR}; ./PostProc.pl -M RESULTS

test2_check:
	-@(${SCRIPTDIR}/DiffNum.pl -b -r=1e-5 \
		${TESTDIR}/RESULTS/SC/log_n000001.log \
		output/test2/SC_log_n000001.log \
		> test2_sc.diff)
	-@(${SCRIPTDIR}/DiffNum.pl -b -r=1e-5 \
		${TESTDIR}/RESULTS/IH/log_n000001.log \
		output/test2/IH_log_n000001.log \
		> test2_ih.diff)
	-@(${SCRIPTDIR}/DiffNum.pl -b -r=1e-5 \
		${TESTDIR}/RESULTS/IH/sat_earth_traj_n000000.sat \
		output/test2/IH_sat_earth_traj_n000000.sat \
		>> test2_ih.diff)
	ls -l test2*.diff

### Test3: GM+IE+IM ###

test3:
	@echo "test3_compile..." > test3_gm.diff
	@echo "test3_compile..." > test3_ie.diff
	@echo "test3_compile..." > test3_im.diff
	make test3_compile
	@echo "test3_rundir..." >> test3_gm.diff
	@echo "test3_rundir..." >> test3_ie.diff
	@echo "test3_rundir..." >> test3_im.diff
	make test3_rundir
	@echo "test3_run..." >> test3_gm.diff
	@echo "test3_run..." >> test3_ie.diff
	@echo "test3_run..." >> test3_im.diff
	make test3_run
	@echo "test3_check..." >> test3_gm.diff
	@echo "test3_check..." >> test3_ie.diff
	@echo "test3_check..." >> test3_im.diff
	make test3_check

test3_compile:
	./Config.pl -v=Empty,GM/BATSRUS,IE/Ridley_serial,IM/RCM2
	./Config.pl -g=GM:8,8,8,400,100 -o=GM:u=Default,e=Mhd
	make SWMF PIDL

test3_rundir:
	rm -rf ${TESTDIR}
	make rundir RUNDIR=${TESTDIR}
	cp Param/PARAM.in.test.GMIEIM ${TESTDIR}/PARAM.in
	cp Param/LAYOUT.in.test.GMIEIM ${TESTDIR}/LAYOUT.in

#	cp Param/midn_05.dat ${TESTDIR}/midn_05.dat
#	cp Param/noon_05.dat ${TESTDIR}/noon_05.dat

# Note: The RCM .dat file is copied to .txt to avoid conversion to .plt
test3_run:
	cd ${TESTDIR}; ${MPIRUN} ./SWMF.exe > runlog
	cp ${TESTDIR}/IM/plots/2d__max_t00000010.dat \
		${TESTDIR}/IM/plots/t10.txt
	cd ${TESTDIR}; ./PostProc.pl -M RESULTS

test3_check:
	-@(${SCRIPTDIR}/DiffNum.pl -b -r=1e-3 -a=1e-8 \
		${TESTDIR}/RESULTS/GM/log_n000001.log \
		output/test3/GM_log_n000001.log \
		> test3_gm.diff)
	-@(${SCRIPTDIR}/DiffNum.pl -b -r=1e-6 \
		${TESTDIR}/RESULTS/IE/logIE.log \
		output/test3/IE_logIE.log \
		> test3_ie.diff)
	gunzip -c output/test3/IM_2d__max_t00000010.dat.gz \
		> ${TESTDIR}/RESULTS/IM/t10.dat
	# Remove date stamp from tecplot files
	cd ${TESTDIR}/RESULTS/IM; \
		perl -pi -e 's/AUXDATA SAVEDATE=.*//' t10.txt t10.dat
	-@(${SCRIPTDIR}/DiffNum.pl -b -r=1e-3 -a=1e-8 \
		${TESTDIR}/RESULTS/IM/t10.txt \
		${TESTDIR}/RESULTS/IM/t10.dat \
		> test3_im.diff)
	ls -l test3*.diff

### ESMF test ###
#
#       Targets for the ESMF compatible executable
#

test_esmf:
	@echo "test_esmf_compile..." > test_esmf.diff
	make test_esmf_compile
	@echo "test_esmf_rundir..." >> test_esmf.diff
	make test_esmf_rundir
	@echo "test_esmf_run..." >> test_esmf.diff
	make test_esmf_run
	@echo "test_esmf_check..." >> test_esmf.diff
	make test_esmf_check

test_esmf_compile:
	./Config.pl -v=Empty,GM/BATSRUS,IE/Ridley_serial
	./Config.pl -g=GM:8,8,8,400,100,IE:91,181 -o=GM:u=Default,e=Mhd
	make ESMF_SWMF

test_esmf_rundir:
	rm -rf ${TESTDIR};
	make rundir RUNDIR=${TESTDIR}
	cd ESMF/ESMF_SWMF; make rundir RUNDIR=${TESTDIR}
	
test_esmf_run: 
	@cd ${TESTDIR}; rm -f PET*ESMF_LogFile
	@cd ${TESTDIR}; ${MPIRUN} ESMF_SWMF.exe > runlog
	@cd ${TESTDIR}; ./PostProc.pl -M RESULTS

test_esmf_check:
	perl -ne 'print if /error/i' ${TESTDIR}/PET*.ESMF_LogFile \
		> test_esmf.diff
	${SCRIPTDIR}/DiffNum.pl -b -r=1e-5 \
		${TESTDIR}/RESULTS/GM/log_n000001.log \
		ESMF/ESMF_SWMF/output/log_n000001.log \
		>> test_esmf.diff
	gunzip -c ESMF/ESMF_SWMF/output/it000321_104510_000.idl.gz \
		> ${TESTDIR}/it000321_104510_000.idl.ref
	${SCRIPTDIR}/DiffNum.pl -b -r=1e-4 \
		${TESTDIR}/RESULTS/IE/it000321_104510_000.idl \
		${TESTDIR}/it000321_104510_000.idl.ref \
		>> test_esmf.diff
	ls -l test_esmf.diff
