#!/bin/csh

if($1 == 'help' || $1 == '-h' || $1 == '-help')then
   echo "Compare covariant configuration with a similar Cartesian configuration."
   echo "The results will be in run_covariant and run_covarcheck."
   echo "The comparison is done with TestCompare.pl and saved into compare.txt"
   echo "Usage:"
   echo ""
   echo "TestCovariant.pl [some test runs]"
   echo ""
   echo "where the argument is a test run typically using TestBatsrus.pl or TestSuite.pl."
   echo "The default test is running TestBatsrus.pl without arguments."
   echo "Examples:"
   echo ""
   echo "TestCovariant                                    # do default test"
   echo "TestCovariant GM/BATSRUS_conf/TestBatsrus.pl -ta # do another test"
   echo "TestCovariant GM/BATSRUS_conf/TestSuite.pl func  # do test suite"
   echo "TestCovariant make                               # just compile"
   echo "TestCovariant echo Configuration done            # just configure"
   exit
endif

if($1 == '')then
   set test='GM/BATSRUS_conf/TestBatsrus.pl'
else
   set test="$*"
endif

if(-d run)then
   echo Rename or remove run directory before running this test.
   exit
endif

cd GM/BATSRUS; rm -rf COVARCHECK; make covarcheck_conf; cd ../..
SetSWMF.pl -v=GM/BATSRUS_conf,IE/Ridley_serial,IM/Empty,IH/Empty,UA/Empty
make clean
$test
if(-d run)then
   rm -rf run_covarcheck
   mv run run_covarcheck
endif

cd GM/BATSRUS; rm -rf COVARIANT; make covariant_conf; cd ../..
SetSWMF.pl -v=GM/BATSRUS_conf
make clean
$test
if(-d run)then
    rm -rf run_covariant compare.txt
    mv run run_covariant
    TestCompare.pl -o=1e-14 run_covariant run_covarcheck > compare.txt
    cat compare.txt
endif
