# Local Makefile.def

localdefault: help # default target

SCRIPTDIR = ${IMDIR}/share/Scripts
LIBDIR    = ${IMDIR}/src
RUNDIR    = ${IMDIR}/run
BINDIR    = ${IMDIR}/src
SHAREDIR  = ${IMDIR}/share/Library/src

NOMPIDIR  = ${IMDIR}/util/NOMPI/src
TIMINGDIR = ${IMDIR}/util/TIMING/src
EMPIRICALIEDIR = ${IMDIR}/util/EMPIRICAL/srcIE
EMPIRICALGMDIR= ${IMDIR}/util/EMPIRICAL/srcGM
