# Local Makefile.def

localdefault: help # default target
DIR       = ${RBDIR}
SCRIPTDIR = ${RBDIR}/share/Scripts
LIBDIR    = ${RBDIR}/src
RUNDIR    = ${RBDIR}/run
BINDIR    = ${RBDIR}/src
SHAREDIR  = ${RBDIR}/share/Library/src

NOMPIDIR  = ${RBDIR}/util/NOMPI/src
TIMINGDIR = ${RBDIR}/util/TIMING/src
EMPIRICALIEDIR = ${RBDIR}/util/EMPIRICAL/srcIE
EMPIRICALGMDIR= ${RBDIR}/util/EMPIRICAL/srcGM
