#
# This job script should be executed from temporary test directory 
#

#PBS -N AMPS_pfe

#PBS -q devel
#PBS -l select=1:ncpus=24:model=has

#PBS -l walltime=2:00:00

#PBS -j oe
#PBS -m e

# Specify group if necessary
#PBS -W group_list=g26135

rm -f AmpsTestComplete 

# Run AMPS tests compiled with GNU, Intel and PGI compilers
#AMPS/utility/TestScripts/Pleiades/RunIntelPleiades.sh test_run &
cd Intel/AMPS
module purge
module load comp-intel/2016.2.181 mpi-sgi tecplot/2017r2
make test_run TESTMPIRUN1="mpiexec -n 1 dplace -s1 -c 0"  MPIRUN="mpiexec -n 8 dplace -s1 -c 0-7" >>& test_amps.log &
cd ../..

#AMPS/utility/TestScripts/Pleiades/RunPGIPleiades.sh test_run &
cd PGI/AMPS
module purge
module load comp-pgi/17.1 mpi-sgi/mpt tecplot/2017r2
make test_run TESTMPIRUN1="mpiexec -n 1 dplace -s1 -c 8"  MPIRUN="mpiexec -n 8 dplace -s1 -c 8-15" >>& test_amps.log &
cd ../..


#AMPS/utility/TestScripts/Pleiades/RunGNUPleiades.sh test_run &
cd GNU/AMPS
module purge
module load gcc/6.2 mpi-sgi tecplot/2017r2
make test_run TESTMPIRUN1="mpiexec -n 1 dplace -s1 -c 16"  MPIRUN="mpiexec -n 8 dplace -s1 -c 16-23" >>& test_amps.log &
cd ../..

wait

echo Done > AmpsTestComplete 
exit

