#
# This job script should be executed from temporary test directory 
#
# set the number of CPU-s by changing select: nProc = select*ncpus

#PBS -N AMPS_pfe

#PBS -q devel
#PBS -l select=1:ncpus=8:model=has

#PBS -l walltime=2:00:00

#PBS -j oe
#PBS -m e

# Specify group if necessary
#PBS -W group_list=g26135

# run AMPS tests compiled with Intel
cd Intel/AMPS
module purge
module load comp-intel/2015.0.090 
module load mpi-openmpi/1.6.5-intel
module load tecplot/360_2013
make test_run MPIRUN=mpiexec >>& test_amps.log
cd ../..