#
# This job script should be executed from temporary test directory 
#
# set the number of CPU-s by changing select: nProc = select*ncpus

#PBS -N AMPS_pfe

#PBS -q devel
#PBS -l select=1:ncpus=8:model=has

#PBS -l walltime=2:00:00

#PBS -j oe
#PBS -m e

# Specify group if necessary
#PBS -W group_list=g26135

# run AMPS tests compiled with PGI
cd PGI/AMPS
module purge
module load comp-pgi/17.1
module load mpi-sgi/mpt
module load tecplot/2017r2
make test_run MPIRUN=mpiexec >>& test_amps.log
cd ../..
echo Done > AmpsTestDone
