#!/bin/csh 
#----------------------------------------------------
# Job script for nightly AMPS tests on 
# TACC's Stampede system.
#----------------------------------------------------
#SBATCH -J AMPS_test      # Job name
#SBATCH -o test_intel.out # Name of stdout output file(%j expands to jobId)
#SBATCH -e %j.err         # Name of stderr output file(%j expands to jobId)

#SBATCH -p development    # submit to the 'large' queue for jobs > 256 nodes
#SBATCH -N 1              # Total number of nodes requested (16 cores/node)
#SBATCH -n 8              # Total number of mpi tasks requested
#SBATCH -t 02:00:00       # Run time (hh:mm:ss) - 1.5 hours

#The next line is required if the user has more than one project
#SBATCH -A TG-AST170027  # Allocation name to charge job against

# run AMPS tests compiled with Intel
cd Intel/AMPS
module load intel
make test_run TESTMPIRUN4="/usr/local/bin/ibrun -n 4" TESTMPIRUN1="/usr/local/bin/ibrun -n 1" MPIRUN="/usr/local/bin/ibrun" >>& test_amps.log
cd ../..

echo Done > AmpsTestDone
