#!/bin/bash
#----------------------------------------------------
# Job script for nightly AMPS tests on 
# TACC's Stampede system.
#----------------------------------------------------
#SBATCH -J AMPS_test   # Job name
#SBATCH -o %j.out      # Name of stdout output file(%j expands to jobId)
#SBATCH -e %j.err      # Name of stderr output file(%j expands to jobId)

#SBATCH -p development # submit to the 'large' queue for jobs > 256 nodes
#SBATCH -N 1           # Total number of nodes requested (16 cores/node)
#SBATCH -n 8           # Total number of mpi tasks requested
#SBATCH -t 02:00:00    # Run time (hh:mm:ss) - 1.5 hours

#The next line is required if the user has more than one project
#SBATCH -A TG-AST140002  # Allocation name to charge job against

# run AMPS tests compiled with GNU
module purge
module load gcc/4.9.1
module load mvapich2/2.1
make test_run MPIRUN=ibrun >>& test_amps.log
cd ../..

# run AMPS tests compiled with Intel
cd Intel/AMPS
module purge
module load comp-intel/2015.0.090 
module load mvapich2/2.1
make test_run MPIRUN=ibrun >>& test_amps.log
cd ../..
