      SUBROUTINE CLFMHE
      use ModCommonVariables
      REAL DBN1(MaxGrid),UBN1(MaxGrid),PBN1(MaxGrid),
     $ U12(MaxGrid),P12(MaxGrid),
     $ D12(MaxGrid),WL(MaxGrid),WR(MaxGrid),PDIFF(MaxGrid),PSUM(MaxGrid)
C----------------------
CLFMHEL
C
C
CALEX      USUM=USURHE+UHEL(1)
CALEX      UDIFF=USURHE-UHEL(1)
CALEX      PDIFF(1)=PSURHE-PHEL(1)
CALEX      PSUM(1)=PSURHE+PHEL(1)
CALEX      DSUM=DSURHE+DHEL(1)
CALEX      A0=SQRT(GAMMA*PSUM(1)*DSUM/4.)
CALEX      P12(1)=(PSUM(1)+A0*UDIFF)/2.
CALEX      U12(1)=(USUM+PDIFF(1)/A0)/2.
CALEX      DD=CVMGP(DSURHE,DHEL(1),U12(1))
CALEX      PP=CVMGP(PSURHE,PHEL(1),U12(1))
CALEX      D12(1)=DD*(GPL1*P12(1)+GMIN1*PP)/(GMIN1*P12(1)+GPL1*PP)
CALEX      WL(1)=USURHE-A0/DSURHE
CALEX      WR(1)=UHEL(1)+A0/DHEL(1)
CALEX      D12(1)=CVMGP(DSURHE,D12(1),WL(1))
CALEX      U12(1)=CVMGP(USURHE,U12(1),WL(1))
CALEX      P12(1)=CVMGP(PSURHE,P12(1),WL(1))
CALEX      U12(1)=CVMGP(U12(1),UHEL(1),WR(1))
CALEX      P12(1)=CVMGP(P12(1),PHEL(1),WR(1))
CALEX      D12(1)=CVMGP(D12(1),DHEL(1),WR(1))
CALEX      DO 8510 K=2,NDIM
CALEX         L=K-1
CALEX         USUM=UHEL(L)+UHEL(K)
CALEX         UDIFF=UHEL(L)-UHEL(K)
CALEX         PDIFF(K)=PHEL(L)-PHEL(K)
CALEX         PSUM(K)=PHEL(L)+PHEL(K)
CALEX         DSUM=DHEL(L)+DHEL(K)
CALEX         A0=SQRT(GAMMA*PSUM(K)*DSUM/4.)
CALEX         P12(K)=(PSUM(K)+A0*UDIFF)/2.
CALEX         U12(K)=(USUM+PDIFF(K)/A0)/2.
CALEX         DD=CVMGP(DHEL(L),DHEL(K),U12(K))
CALEX         PP=CVMGP(PHEL(L),PHEL(K),U12(K))
CALEX         D12(K)=DD*(GPL1*P12(K)+GMIN1*PP)/(GMIN1*P12(K)+GPL1*PP)
CALEX         WL(K)=UHEL(L)-A0/DHEL(L)
CALEX         WR(K)=UHEL(K)+A0/DHEL(K)
CALEX         D12(K)=CVMGP(DHEL(L),D12(K),WL(K))
CALEX         U12(K)=CVMGP(UHEL(L),U12(K),WL(K))
CALEX         P12(K)=CVMGP(PHEL(L),P12(K),WL(K))
CALEX         U12(K)=CVMGP(U12(K),UHEL(K),WR(K))
CALEX         P12(K)=CVMGP(P12(K),PHEL(K),WR(K))
CALEX         D12(K)=CVMGP(D12(K),DHEL(K),WR(K))
CALEX 8510 CONTINUE
CALEX      USUM=UHEL(NDIM)+UBGNHE
CALEX      UDIFF=UHEL(NDIM)-UBGNHE
CALEX      PDIFF(NDIM1)=PHEL(NDIM)-PBGNHE
CALEX      PSUM(NDIM1)=PHEL(NDIM)+PBGNHE
CALEX      DSUM=DHEL(NDIM)+DBGNHE
CALEX      A0=SQRT(GAMMA*PSUM(NDIM1)*DSUM/4.)
CALEX      P12(NDIM1)=(PSUM(NDIM1)+A0*UDIFF)/2.
CALEX      U12(NDIM1)=(USUM+PDIFF(NDIM1)/A0)/2.
CALEX      DD=CVMGP(DHEL(NDIM),DBGNHE,U12(NDIM1))
CALEX      PP=CVMGP(PHEL(NDIM),PBGNHE,U12(NDIM1))
CALEX      D12(NDIM1)=DD*(GPL1*P12(NDIM1)+GMIN1*PP)/(GMIN1*P12(NDIM1)
CALEX     $+GPL1*PP)
CALEX      WL(NDIM1)=UHEL(NDIM)-A0/DHEL(NDIM)
CALEX      WR(NDIM1)=UBGNHE+A0/DBGNHE
CALEX      D12(NDIM1)=CVMGP(DHEL(NDIM),D12(NDIM1),WL(NDIM1))
CALEX      U12(NDIM1)=CVMGP(UHEL(NDIM),U12(NDIM1),WL(NDIM1))
CALEX      P12(NDIM1)=CVMGP(PHEL(NDIM),P12(NDIM1),WL(NDIM1))
CALEX      U12(NDIM1)=CVMGP(U12(NDIM1),UBGNHE,WR(NDIM1))
CALEX      P12(NDIM1)=CVMGP(P12(NDIM1),PBGNHE,WR(NDIM1))
CALEX      D12(NDIM1)=CVMGP(D12(NDIM1),DBGNHE,WR(NDIM1))
CALEX      DO 8530 K=1,NDIM1
CALEX         DBN1(K)=U12(K)*D12(K)
CALEX         UFL=U12(K)*DBN1(K)
CALEX         PFL=GMIN2*U12(K)*UFL
CALEX         UBN1(K)=UFL+P12(K)
CALEX         PBN1(K)=PFL+GAMMA*U12(K)*P12(K)
CALEX8530  CONTINUE
CALEXc
CALEX      XHTM=EXP(-(TIME-300.)**2/2./150./150.)
c

      DO 8570 K=1,NDIM
         KK=K+1
C         CELLNW(11,K)=DHEL(K)-DTR1*(AR23(K)*DBN1(KK)-AR12(K)*DBN1(K))
C     $        +DTX1*ADMSHE(K)
C         CELLNW(9,K)=(UHEL(K)*DHEL(K)-DTR1*(AR23(K)*UBN1(KK)-AR12(K)*
C     $        UBN1(K))+DTX1*(DAREA(K)*PHEL(K)+FCLSHE(K)))/CELLNW(11,K)
C         CELLNW(10,K)=PHEL(K)-GMIN2*(CELLNW(9,K)**2*CELLNW(11,K)-
C     $       UHEL(K)**2*DHEL(K))-DTR1*(AR23(K)*PBN1(KK)-AR12(K)*PBN1(K))
C     $        +DTX1*GMIN1*(ECLSHE(K)+XHTM*QHEL(K)*DHEL(K))
C         CELLNW(12,K)=CELLNW(10,K)/RGASHE/CELLNW(11,K)
         
c         CELLNW(11,K)=XMSHE*jp2/kc1
         CELLNW(11,k)=0.
         CELLNW(9,K)=0.
         CELLNW(10,K)=RGASHE*CELLNW(11,K)*0.
         CELLNW(12,K)=0.
         
 8570 CONTINUE
      RETURN
      END
