CELL_CENTERED_LINEAR_INTERPOLATION_SRC=

CELL_CENTERED_LINEAR_INTERPOLATION_OBJ_LOCAL=\
  CON_stop.o                                 \
  cell_centered_linear_interpolation_cpp.o   \
  cell_centered_linear_interpolation_f90.o 

CELL_CENTERED_LINEAR_INTERPOLATION_OBJ_EXTERNAL=\
  ModKind.o                                     \
  ModInterpolateAMR.o 


cell_centered_linear_interpolation : 
	${COMPILE.f90} ${Cflag3} CON_stop.f90
	${COMPILE.f90} ${Cflag3} ${CELL_CENTERED_LINEAR_INTERPOLATION_SRC}/ModKind.f90
	${COMPILE.f90} ${Cflag3} ${CELL_CENTERED_LINEAR_INTERPOLATION_SRC}/ModInterpolateAMR.f90
	${COMPILE.f90} ${Cflag3} cell_centered_linear_interpolation_f90.f90
	${COMPILE.mpicxx} ${FLAGC} cell_centered_linear_interpolation_cpp.cpp -o cell_centered_linear_interpolation_cpp.o
	ar -src cell_centered_linear_interpolation_amr.a          \
               ${CELL_CENTERED_LINEAR_INTERPOLATION_OBJ_EXTERNAL} \
               ${CELL_CENTERED_LINEAR_INTERPOLATION_OBJ_LOCAL}
