CELL_CENTERED_LINEAR_INTERPOLATION_SRC=

CELL_CENTERED_LINEAR_INTERPOLATION_OBJ_LOCAL=\
  cell_centered_linear_interpolation_cpp.o   \
  cell_centered_linear_interpolation_f90.o 

CELL_CENTERED_LINEAR_INTERPOLATION_OBJ_EXTERNAL=\
  ModKind.o                                     \
  ModMpiOrig.o					\
  ModMpiInterfaces.o 				\
  ModMpi.o					\
  ModIoUnit.o					\
  ModUtility_c.o 				\
  ModUtility.o					\
  ModInterpolateAMR.o


cell_centered_linear_interpolation :
	$(foreach FILE, ${CELL_CENTERED_LINEAR_INTERPOLATION_OBJ_EXTERNAL},\
	cd ${CELL_CENTERED_LINEAR_INTERPOLATION_SRC}; ${MAKE} ${FILE};)
	$(foreach FILE, ${CELL_CENTERED_LINEAR_INTERPOLATION_OBJ_EXTERNAL},\
	mv ${CELL_CENTERED_LINEAR_INTERPOLATION_SRC}/${FILE} .;)
	${COMPILE.f90} ${Cflag3} -J${CELL_CENTERED_LINEAR_INTERPOLATION_SRC} cell_centered_linear_interpolation_f90.f90
	${COMPILE.mpicxx} ${FLAGC} cell_centered_linear_interpolation_cpp.cpp -o cell_centered_linear_interpolation_cpp.o
	ar -src cell_centered_linear_interpolation_amr.a          \
               ${CELL_CENTERED_LINEAR_INTERPOLATION_OBJ_EXTERNAL} \
               ${CELL_CENTERED_LINEAR_INTERPOLATION_OBJ_LOCAL}
