      SUBROUTINE CLFMHE


      use ModCommonVariables


      REAL DBN1(MaxGrid),UBN1(MaxGrid),PBN1(MaxGrid),
     $ U12(MaxGrid),P12(MaxGrid),
     $ D12(MaxGrid),WL(MaxGrid),WR(MaxGrid),PDIFF(MaxGrid),PSUM(MaxGrid)
C----------------------
CLFMHEL
C
C
      USUM=USURHE+UHEL(1)
      UDIFF=USURHE-UHEL(1)
      PDIFF(1)=PSURHE-PHEL(1)
      PSUM(1)=PSURHE+PHEL(1)
      DSUM=DSURHE+DHEL(1)
      A0=SQRT(GAMMA*PSUM(1)*DSUM/4.)
      P12(1)=(PSUM(1)+A0*UDIFF)/2.
      U12(1)=(USUM+PDIFF(1)/A0)/2.
      DD=CVMGP(DSURHE,DHEL(1),U12(1))
      PP=CVMGP(PSURHE,PHEL(1),U12(1))
      D12(1)=DD*(GPL1*P12(1)+GMIN1*PP)/(GMIN1*P12(1)+GPL1*PP)
      WL(1)=USURHE-A0/DSURHE
      WR(1)=UHEL(1)+A0/DHEL(1)
      D12(1)=CVMGP(DSURHE,D12(1),WL(1))
      U12(1)=CVMGP(USURHE,U12(1),WL(1))
      P12(1)=CVMGP(PSURHE,P12(1),WL(1))
      U12(1)=CVMGP(U12(1),UHEL(1),WR(1))
      P12(1)=CVMGP(P12(1),PHEL(1),WR(1))
      D12(1)=CVMGP(D12(1),DHEL(1),WR(1))
      DO 8510 K=2,NDIM
         L=K-1
         USUM=UHEL(L)+UHEL(K)
         UDIFF=UHEL(L)-UHEL(K)
         PDIFF(K)=PHEL(L)-PHEL(K)
         PSUM(K)=PHEL(L)+PHEL(K)
         DSUM=DHEL(L)+DHEL(K)
         A0=SQRT(GAMMA*PSUM(K)*DSUM/4.)
         P12(K)=(PSUM(K)+A0*UDIFF)/2.
         U12(K)=(USUM+PDIFF(K)/A0)/2.
         DD=CVMGP(DHEL(L),DHEL(K),U12(K))
         PP=CVMGP(PHEL(L),PHEL(K),U12(K))
         D12(K)=DD*(GPL1*P12(K)+GMIN1*PP)/(GMIN1*P12(K)+GPL1*PP)
         WL(K)=UHEL(L)-A0/DHEL(L)
         WR(K)=UHEL(K)+A0/DHEL(K)
         D12(K)=CVMGP(DHEL(L),D12(K),WL(K))
         U12(K)=CVMGP(UHEL(L),U12(K),WL(K))
         P12(K)=CVMGP(PHEL(L),P12(K),WL(K))
         U12(K)=CVMGP(U12(K),UHEL(K),WR(K))
         P12(K)=CVMGP(P12(K),PHEL(K),WR(K))
         D12(K)=CVMGP(D12(K),DHEL(K),WR(K))
 8510 CONTINUE
      USUM=UHEL(NDIM)+UBGNHE
      UDIFF=UHEL(NDIM)-UBGNHE
      PDIFF(NDIM1)=PHEL(NDIM)-PBGNHE
      PSUM(NDIM1)=PHEL(NDIM)+PBGNHE
      DSUM=DHEL(NDIM)+DBGNHE
      A0=SQRT(GAMMA*PSUM(NDIM1)*DSUM/4.)
      P12(NDIM1)=(PSUM(NDIM1)+A0*UDIFF)/2.
      U12(NDIM1)=(USUM+PDIFF(NDIM1)/A0)/2.
      DD=CVMGP(DHEL(NDIM),DBGNHE,U12(NDIM1))
      PP=CVMGP(PHEL(NDIM),PBGNHE,U12(NDIM1))
      D12(NDIM1)=DD*(GPL1*P12(NDIM1)+GMIN1*PP)/(GMIN1*P12(NDIM1)
     $+GPL1*PP)
      WL(NDIM1)=UHEL(NDIM)-A0/DHEL(NDIM)
      WR(NDIM1)=UBGNHE+A0/DBGNHE
      D12(NDIM1)=CVMGP(DHEL(NDIM),D12(NDIM1),WL(NDIM1))
      U12(NDIM1)=CVMGP(UHEL(NDIM),U12(NDIM1),WL(NDIM1))
      P12(NDIM1)=CVMGP(PHEL(NDIM),P12(NDIM1),WL(NDIM1))
      U12(NDIM1)=CVMGP(U12(NDIM1),UBGNHE,WR(NDIM1))
      P12(NDIM1)=CVMGP(P12(NDIM1),PBGNHE,WR(NDIM1))
      D12(NDIM1)=CVMGP(D12(NDIM1),DBGNHE,WR(NDIM1))
      DO 8530 K=1,NDIM1
         DBN1(K)=U12(K)*D12(K)
         UFL=U12(K)*DBN1(K)
         PFL=GMIN2*U12(K)*UFL
         UBN1(K)=UFL+P12(K)
         PBN1(K)=PFL+GAMMA*U12(K)*P12(K)
8530  CONTINUE
c
      XHTM=EXP(-(TIME-300.)**2/2./150./150.)
c
      DO 8570 K=1,NDIM
         KK=K+1
         CELLNW(11,K)=DHEL(K)-DTR1*(AR23(K)*DBN1(KK)-AR12(K)*DBN1(K))
     $        +DTX1*ADMSHE(K)
         CELLNW(9,K)=(UHEL(K)*DHEL(K)-DTR1*(AR23(K)*UBN1(KK)-AR12(K)*
     $        UBN1(K))+DTX1*(DAREA(K)*PHEL(K)+FCLSHE(K)))/CELLNW(11,K)
         CELLNW(10,K)=PHEL(K)-GMIN2*(CELLNW(9,K)**2*CELLNW(11,K)-
     $       UHEL(K)**2*DHEL(K))-DTR1*(AR23(K)*PBN1(KK)-AR12(K)*PBN1(K))
     $        +DTX1*GMIN1*(ECLSHE(K)+XHTM*QHEL(K)*DHEL(K))
         CELLNW(12,K)=CELLNW(10,K)/RGASHE/CELLNW(11,K)
 8570 CONTINUE
      RETURN
      END
