      SUBROUTINE ELFLDW
      REAL PRO(MaxGrid),PRHE(MaxGrid),PRH(MaxGrid),PRE(MaxGrid),PR(MaxGrid)
      use ModCommonVariables

C
C
      PRO(1)=USURFO**2*DSURFO
      PRHE(1)=USURHE**2*DSURHE
      PRH(1)=USURFH**2*DSURFH
      PRE(1)=USURFE**2*DSURFE
      PR(1)=PSURFE+PRE(1)-RTHDEL*(PSURFH+PRH(1))-RTOXEL*
     $(PSURFO+PRO(1))-RTHEEL*(PSURHE+PRHE(1))
      PRO(NDIMM)=UBGNDO**2*DBGNDO
      PRHE(NDIMM)=UBGNHE**2*DBGNHE
      PRH(NDIMM)=UBGNDH**2*DBGNDH
      PRE(NDIMM)=UBGNDE**2*DBGNDE
      PR(NDIMM)=PBGNDE+PRE(NDIMM)-RTHDEL*(PBGNDH+PRH(NDIMM))
     $-RTOXEL*(PBGNDO+PRO(NDIMM))-RTHEEL*(PBGNHE+PRHE(NDIMM))
      DO 20 K=1,NDIM
         KK=K+1
         PRO(KK)=UOXYG(K)**2*DOXYG(K)
         PRHE(KK)=UHEL(K)**2*DHEL(K)
         PRH(KK)=UHYD(K)**2*DHYD(K)
         PRE(KK)=UELECT(K)**2*DELECT(K)
         PR(KK)=PELECT(K)+PRE(KK)-RTHDEL*(PHYD(K)+PRH(KK))
     $        -RTOXEL*(POXYG(K)+PRO(KK))-RTHEEL*(PHEL(K)+PRHE(KK))
 20   CONTINUE
      DZ=0.5/DRBND
      DO 30 K=1,NDIM
         L=K+1
         M=K+2
         DNOM=4.803242E-10*(DHYD(K)/XMSH+DOXYG(K)/XMSO+DHEL(K)/XMSHE)
         EZ=FCLSNE(K)-RTHDEL*FCLSNH(K)-RTOXEL*FCLSNO(K)
     $        -RTHEEL*FCLSHE(K)
         EZ=EZ-DAREA(K)*(PRE(L)-RTHDEL*PRH(L)-RTOXEL*PRO(L)
     $        -RTHEEL*PRHE(L))
         EZ=EZ+RTHDEL*(UELECT(K)-UHYD(K))*ADMSH(K)+
     ;        RTOXEL*(UELECT(K)-UOXYG(K))*ADMSO(K)+
     ;        RTHEEL*(UELECT(K)-UHEL(K))*ADMSHE(K)
         EFIELD(K)=(EZ-DZ*(PR(M)-PR(K)))/DNOM
 30   CONTINUE
      EFIELD(NDIM)=2.13E-7*CURRMX/TELECT(NDIM)**1.5
      IF (EFIELD(NDIM).LT.0.) EFIELD(NDIM)=0.
40    DO 50 K=1,NDIM
         FCLSNO(K)=FCLSNO(K)+ADMSO(K)*UOXYG(K)+DOXYG(K)*
     ;        (GRAVTY(K)+4.803242E-10*EFIELD(K)/XMSO)
         FCLSHE(K)=FCLSHE(K)+ADMSHE(K)*UHEL(K)+DHEL(K)*
     ;        (GRAVTY(K)+4.803242E-10*EFIELD(K)/XMSHE)
         FCLSNH(K)=FCLSNH(K)+ADMSH(K)*UHYD(K)+DHYD(K)*
     ;        (GRAVTY(K)+4.803242E-10*EFIELD(K)/XMSH)
         ECLSNO(K)=ECLSNO(K)+UOXYG(K)*(FCLSNO(K)-0.5*UOXYG(K)*ADMSO(K))
         ECLSHE(K)=ECLSHE(K)+UHEL(K)*(FCLSHE(K)-0.5*UHEL(K)*ADMSHE(K))
         ECLSNH(K)=ECLSNH(K)+UHYD(K)*(FCLSNH(K)-0.5*UHYD(K)*ADMSH(K))
 50   CONTINUE
      RETURN
      END
