C        OPEN(UNIT=12,FILE='MSIS86.DAT',FORM='FORMATTED',STATUS='OLD')
C        READ(12,1290) PT1,PT2,PT3,PA1,PA2,PA3,PB1,PB2,PB3,PC1,PC2,
C     &    PC3,PD1,PD2,PD3,PE1,PE2,PE3,PF1,PF2,PF3,PG1,PG2,PG3,PH1,
C     &    PH2,PH3,PI1,PTM,PDM
CCCCCCCCCCCCC IN PC VERSION: 1290    FORMAT(5E13.6)
C1290  FORMAT(1X,5E13.6)
CCCCCCCCCCCCC------------------------------------------------------------------
      SUBROUTINE GGM(ART,XLG,BG,XLM,BM)
C CALCULATES GEOMAGNETIC LONGITUDE (XLM) AND LATITUDE (BM)
C FROM GEOGRAFIC LONGITUDE (XLG) AND LATITUDE (BG) FOR ART=0
C AND REVERSE FOR ART=1. ALL ANGLES IN DEGREE.
C LATITUDE:-90 TO 90. LONGITUDE:0 TO 360 EAST.
      INTEGER ART
      FAKTOR=.0174532925
      ZPI=FAKTOR*360.
      CBG=11.4*FAKTOR
      CI=COS(CBG)
      SI=SIN(CBG)
      IF(ART.EQ.0) GOTO 10
      CBM=COS(BM*FAKTOR)
      SBM=SIN(BM*FAKTOR)
      CLM=COS(XLM*FAKTOR)
      SLM=SIN(XLM*FAKTOR)
      SBG=SBM*CI-CBM*CLM*SI
      BG=ASIN(SBG)
      CBG=COS(BG)
      SLG=(CBM*SLM)/CBG
      CLG=(SBM*SI+CBM*CLM*CI)/CBG
      IF(CLG.GT.1.) CLG=1.
      IF(CLG.LT.-1.) CLG=-1.
      XLG=ACOS(CLG)
      IF(SLG.LT.0.0) XLG=ZPI-ACOS(CLG)
      BG=BG/FAKTOR
      XLG=XLG/FAKTOR
      XLG=XLG-69.8
      IF(XLG.LT.0.0) XLG=XLG+360.0
        RETURN
10    YLG=XLG+69.8
      CBG=COS(BG*FAKTOR)
      SBG=SIN(BG*FAKTOR)
      CLG=COS(YLG*FAKTOR)
      SLG=SIN(YLG*FAKTOR)
      SBM=SBG*CI+CBG*CLG*SI
      BM=ASIN(SBM)
      CBM=COS(BM)
      SLM=(CBG*SLG)/CBM
      CLM=(-SBG*SI+CBG*CLG*CI)/CBM
      XLM=ACOS(CLM)
      IF(SLM.LT..0) XLM=ZPI-ACOS(CLM)
      BM=BM/FAKTOR
      XLM=XLM/FAKTOR
      END
