OBJECTS_PLANET = \
	PhotoElectronPW_planet.o\
	glowex_planet.o\
	prnthe_planet.o\
	prntCollision_planet.o\
	rcolum_planet.o\
	startupPW_planet.o\
	fieldm_planet.o\
	precipitationPW_planet.o\
	solzen_planet.o\
	suncor_planet.o\
	clfmhe_planet.o\
	ggm_planet.o\
	sperfc_planet.o\
	chap_planet.o\
	IonHeatFluxPW_planet.o\
	neutral_atmosphere_planet.o\
	ssflux_planet.o\
	vcd_planet.o\
	collisionPW_planet.o\
	newboundaryPW_planet.o\
	msis90_planet.o
	
