MODULES_PLANET = \
	ModGlow.o

OBJECTS_PLANET = \
	PhotoElectronPW_planet.o\
	glowex_planet.o\
	rcolum_planet.o\
	startupPW_planet.o\
	fieldm_planet.o\
	precipitationPW_planet.o\
	solzen_planet.o\
	suncor_planet.o\
	sperfc_planet.o\
	chap_planet.o\
	neutral_atmosphere_planet.o\
	ssflux_planet.o\
	vcd_planet.o\
	collisionPW_planet.o\
	upper_heat_conduction.o\
	ggm_planet.o

	
