      SUBROUTINE PRNTHE

      use ModCommonVariables

C     
C
C
      WRITE(iUnitOutput,1010) TIME,DT,NSTEP
1010  FORMAT(1H1,10X,'TIME=',1PE12.4,'SEC',10X,'TIME STEP=',1PE12.4,
     ;'SEC',10X,'NSTEP=',I6)
      WRITE(iUnitOutput,1013)
1013  FORMAT(1H0,47X,'NEW HE+ PARAMETERS')
      WRITE(iUnitOutput,1011)
1011  FORMAT(16X,'ALT',10X,'VELOCITY',8X,'MACH NO',9X,'DENSITY',9X,
     ;'PRESSURE',6X,'TEMPERATURE',5X,' NET SOURCE'/)
      K=0
      XM=USURHE/WSURHE
      DNS1=DSURHE/XMSHE
      WRITE(iUnitOutput,1012) K,ALTMIN,USURHE,XM,DNS1,PSURHE,TSURHE
1012  FORMAT(3X,I3,0PF14.2,2X,5(1PE16.5))
      NDMQ=NPT1
      IF (NDIM.LT.NPT2) NDMQ=NDIM
      DO 30 K=1,NDMQ
      US=SQRT(GAMMA*PHEL(K)/DHEL(K))
      XM=UHEL(K)/US
      ADM=ADMSHE(K)/XMSHE
      DNS1=DHEL(K)/XMSHE
      WRITE(iUnitOutput,1022) K,ALTD(K),UHEL(K),XM,DNS1,PHEL(K),THEL(K),ADM
1022  FORMAT(3X,I3,0PF14.2,2X,6(1PE16.5))
30    CONTINUE
      IF (NDIM.LT.NPT2) GO TO 100
      NDMQ=NPT3
      IF (NDIM.LT.NPT4) NDMQ=NDIM
      DO 40 K=NPT2,NDMQ,2
      US=SQRT(GAMMA*PHEL(K)/DHEL(K))
      XM=UHEL(K)/US
      ADM=ADMSHE(K)/XMSHE
      DNS1=DHEL(K)/XMSHE
      WRITE(iUnitOutput,1022) K,ALTD(K),UHEL(K),XM,DNS1,PHEL(K),THEL(K),ADM
40    CONTINUE
      IF (NDIM.LT.NPT4) GO TO 100
      NDMQ=NPT5
      IF (NDIM.LT.NPT6) NDMQ=NDIM
      DO 50 K=NPT4,NDMQ,5
      US=SQRT(GAMMA*PHEL(K)/DHEL(K))
      XM=UHEL(K)/US
      ADM=ADMSHE(K)/XMSHE
      DNS1=DHEL(K)/XMSHE
      WRITE(iUnitOutput,1022) K,ALTD(K),UHEL(K),XM,DNS1,PHEL(K),THEL(K),ADM
50    CONTINUE
      IF (NDIM.LT.NPT6) GO TO 100
      DO 60 K=NPT6,NDIM,10
      US=SQRT(GAMMA*PHEL(K)/DHEL(K))
      XM=UHEL(K)/US
      ADM=ADMSHE(K)/XMSHE
      DNS1=DHEL(K)/XMSHE
      WRITE(iUnitOutput,1022) K,ALTD(K),UHEL(K),XM,DNS1,PHEL(K),THEL(K),ADM
60    CONTINUE
100   CONTINUE
      K=NDIM1
      XM=UBGNHE/WBGNHE
      DNS1=DBGNHE/XMSHE
      WRITE(iUnitOutput,1012) K,ALTMAX,UBGNHE,XM,DNS1,PBGNHE,TBGNHE
      RETURN
      END
