# Makefile for AMPS stand-alone nightly tests
# for each test a separate folder run_test_<NAME> is created 
# and executables are copied there

include ${MYDIR}/MakefileTest/makefile.test.moon

test_help:
	@echo "    test_all                 (run all tests with ${MPIRUN})"
	@echo "    test_all MPIRUN=         (run all tests with serially)"
	@echo "    test_moon                (run Moon test with ${MPIRUN})"


test_all:
	@rm -f *.diff
	-@(MAKE test_moon)

test_compile:
	@rm -rf *.diff
	$(MAKE) test_moon_compile
	$(MAKE) test_moon_rundir

test_run:
	$(MAKE) test_moon_run
	$(MAKE) test_moon_check

