
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      
      FUNCTION CVMGP(A,B,C)

      IF(C.GE.0.)THEN
         CVMGP=A
      ELSE
         CVMGP=B
      ENDIF
      RETURN

      END
