# Local Makefile.def

localdefault: help # default target

DIR       = ${PWDIR}
SCRIPTDIR = ${PWDIR}/share/Scripts
LIBDIR    = ${PWDIR}/src
RUNDIR    = ${PWDIR}/run
BINDIR    = ${PWDIR}/bin
INCLDIR   = ${DIR}/share/include
SHAREDIR  = ${PWDIR}/share/Library/src
STETDIR   = ${PWDIR}/srcSTET
TWOSTREAMDIR   = ${PWDIR}/srcTWOSTREAM

TIMINGDIR = ${PWDIR}/util/TIMING/src
EMPIRICALIEDIR = ${PWDIR}/util/EMPIRICAL/srcIE
EMPIRICALUADIR = ${PWDIR}/util/EMPIRICAL/srcUA
DATAREADINDICESDIR = ${PWDIR}/util/DATAREAD/srcIndices
