# Local Makefile.def

localdefault: help # default target

SCRIPTDIR = ${PWDIR}/share/Scripts
LIBDIR    = ${PWDIR}/src
RUNDIR    = ${PWDIR}/run
BINDIR    = ${PWDIR}/bin
SHAREDIR  = ${PWDIR}/share/Library/src

TIMINGDIR = ${PWDIR}/util/TIMING/src
EMPIRICALIEDIR = ${PWDIR}/util/EMPIRICAL/srcIE
DATAREADINDICESDIR = ${PWDIR}/util/DATAREAD/srcIndices
