
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      SUBROUTINE PRNTOP
      use ModCommonVariables
C
C
C
      WRITE(iUnitOutput,1010) TIME,DT,NSTEP
1010  FORMAT(1H1,10X,'TIME=',1PE12.4,'SEC',10X,'TIME STEP=',1PE12.4,
     ;'SEC',10X,'NSTEP=',I6)
      WRITE(iUnitOutput,1013)
1013  FORMAT(1H0,47X,'NEW O+ PARAMETERS')
      WRITE(iUnitOutput,1011)
1011  FORMAT(16X,'ALT',10X,'VELOCITY',8X,'MACH NO',9X,'DENSITY',9X,
     ;'PRESSURE',6X,'TEMPERATURE',5X,' NET SOURCE'/)
      K=0
      XM=USURFO/WSURFO
      DNS1=DSURFO/XMSO
      WRITE(iUnitOutput,1012) K,ALTMIN,USURFO,XM,DNS1,PSURFO,TSURFO
1012  FORMAT(3X,I3,0PF14.2,2X,5(1PE16.5))
      NDMQ=NPT1
      IF (NDIM.LT.NPT2) NDMQ=NDIM
      DO 30 K=1,NDMQ
      US=SQRT(GAMMA*POXYG(K)/DOXYG(K))
      XM=UOXYG(K)/US
      ADM=ADMSO(K)/XMSO
      DNS1=DOXYG(K)/XMSO
      WRITE(iUnitOutput,1022) K,ALTD(K),UOXYG(K),XM,DNS1,POXYG(K),TOXYG(K),ADM
1022  FORMAT(3X,I3,0PF14.2,2X,6(1PE16.5))
30    CONTINUE
      IF (NDIM.LT.NPT2) GO TO 100
      NDMQ=NPT3
      IF (NDIM.LT.NPT4) NDMQ=NDIM
      DO 40 K=NPT2,NDMQ,2
      US=SQRT(GAMMA*POXYG(K)/DOXYG(K))
      XM=UOXYG(K)/US
      ADM=ADMSO(K)/XMSO
      DNS1=DOXYG(K)/XMSO
      WRITE(iUnitOutput,1022) K,ALTD(K),UOXYG(K),XM,DNS1,POXYG(K),TOXYG(K),ADM
40    CONTINUE
      IF (NDIM.LT.NPT4) GO TO 100
      NDMQ=NPT5
      IF (NDIM.LT.NPT6) NDMQ=NDIM
      DO 50 K=NPT4,NDMQ,5
      US=SQRT(GAMMA*POXYG(K)/DOXYG(K))
      XM=UOXYG(K)/US
      ADM=ADMSO(K)/XMSO
      DNS1=DOXYG(K)/XMSO
      WRITE(iUnitOutput,1022) K,ALTD(K),UOXYG(K),XM,DNS1,POXYG(K),TOXYG(K),ADM
50    CONTINUE
      IF (NDIM.LT.NPT6) GO TO 100
      DO 60 K=NPT6,NDIM,10
      US=SQRT(GAMMA*POXYG(K)/DOXYG(K))
      XM=UOXYG(K)/US
      ADM=ADMSO(K)/XMSO
      DNS1=DOXYG(K)/XMSO
      WRITE(iUnitOutput,1022) K,ALTD(K),UOXYG(K),XM,DNS1,POXYG(K),TOXYG(K),ADM
60    CONTINUE
100   CONTINUE
      K=NDIM1
      XM=UBGNDO/WBGNDO
      DNS1=DBGNDO/XMSO
      WRITE(iUnitOutput,1012) K,ALTMAX,UBGNDO,XM,DNS1,PBGNDO,TBGNDO
      RETURN
      END

      SUBROUTINE PRNTHP
      use ModCommonVariables
C
C
C
C
      WRITE(iUnitOutput,1010) TIME,DT,NSTEP
1010  FORMAT(1H1,10X,'TIME=',1PE12.4,'SEC',10X,'TIME STEP=',1PE12.4,
     ;'SEC',10X,'NSTEP=',I6)
      WRITE(iUnitOutput,1013)
1013  FORMAT(1H0,47X,'NEW H+ PARAMETERS')
      WRITE(iUnitOutput,1011)
1011  FORMAT(16X,'ALT',10X,'VELOCITY',8X,'MACH NO',9X,'DENSITY',9X,
     ;'PRESSURE',6X,'TEMPERATURE',5X,' NET SOURCE'/)
      K=0
      XM=USURFH/WSURFH
      DNS1=DSURFH/XMSH
      WRITE(iUnitOutput,1012) K,ALTMIN,USURFH,XM,DNS1,PSURFH,TSURFH
1012  FORMAT(3X,I3,0PF14.2,2X,5(1PE16.5))
      NDMQ=NPT1
      IF (NDIM.LT.NPT2) NDMQ=NDIM
      DO 30 K=1,NDMQ
      US=SQRT(GAMMA*PHYD(K)/DHYD(K))
      XM=UHYD(K)/US
      ADM=ADMSH(K)/XMSH
      DNS1=DHYD(K)/XMSH
      WRITE(iUnitOutput,1022) K,ALTD(K),UHYD(K),XM,DNS1,PHYD(K),THYD(K),ADM
1022  FORMAT(3X,I3,0PF14.2,2X,6(1PE16.5))
30    CONTINUE
      IF (NDIM.LT.NPT2) GO TO 100
      NDMQ=NPT3
      IF (NDIM.LT.NPT4) NDMQ=NDIM
      DO 40 K=NPT2,NDMQ,2
      US=SQRT(GAMMA*PHYD(K)/DHYD(K))
      XM=UHYD(K)/US
      ADM=ADMSH(K)/XMSH
      DNS1=DHYD(K)/XMSH
      WRITE(iUnitOutput,1022) K,ALTD(K),UHYD(K),XM,DNS1,PHYD(K),THYD(K),ADM
40    CONTINUE
      IF (NDIM.LT.NPT4) GO TO 100
      NDMQ=NPT5
      IF (NDIM.LT.NPT6) NDMQ=NDIM
      DO 50 K=NPT4,NDMQ,5
      US=SQRT(GAMMA*PHYD(K)/DHYD(K))
      XM=UHYD(K)/US
      ADM=ADMSH(K)/XMSH
      DNS1=DHYD(K)/XMSH
      WRITE(iUnitOutput,1022) K,ALTD(K),UHYD(K),XM,DNS1,PHYD(K),THYD(K),ADM
50    CONTINUE
      IF (NDIM.LT.NPT6) GO TO 100
      DO 60 K=NPT6,NDIM,10
      US=SQRT(GAMMA*PHYD(K)/DHYD(K))
      XM=UHYD(K)/US
      ADM=ADMSH(K)/XMSH
      DNS1=DHYD(K)/XMSH
      WRITE(iUnitOutput,1022) K,ALTD(K),UHYD(K),XM,DNS1,PHYD(K),THYD(K),ADM
60    CONTINUE
100   CONTINUE
      K=NDIM1
      XM=UBGNDH/WBGNDH
      DNS1=DBGNDH/XMSH
      WRITE(iUnitOutput,1012) K,ALTMAX,UBGNDH,XM,DNS1,PBGNDH,TBGNDH
      RETURN
      END
      SUBROUTINE PRNTEL
      use ModCommonVariables
C
C
C
      WRITE(iUnitOutput,1010) TIME,DT,NSTEP
1010  FORMAT(1H1,10X,'TIME=',1PE12.4,'SEC',10X,'TIME STEP=',1PE12.4,
     ;'SEC',10X,'NSTEP=',I6)
      WRITE(iUnitOutput,1013)
1013  FORMAT(1H0,47X,'NEW ELECTRON PARAMETERS')
      WRITE(iUnitOutput,1011)
1011  FORMAT(16X,'ALT',10X,'VELOCITY',8X,'MACH NO',9X,'DENSITY',9X,
     ;'PRESSURE',6X,'TEMPERATURE',5X,' NET SOURCE'/)
      K=0
      XM=USURFE/WSURFE
      DNS1=DSURFE/XMSE
      WRITE(iUnitOutput,1012) K,ALTMIN,USURFE,XM,DNS1,PSURFE,TSURFE
1012  FORMAT(3X,I3,0PF14.2,2X,5(1PE16.5))
      NDMQ=NPT1
      IF (NDIM.LT.NPT2) NDMQ=NDIM
      DO 30 K=1,NDMQ
      US=SQRT(GAMMA*PELECT(K)/DELECT(K))
      XM=UELECT(K)/US
      ADM=ADMSE(K)/XMSE
      DNS1=DELECT(K)/XMSE
      WRITE(iUnitOutput,1022) K,ALTD(K),UELECT(K),XM,DNS1,PELECT(K),TELECT(K),ADM
1022  FORMAT(3X,I3,0PF14.2,2X,6(1PE16.5))
30    CONTINUE
      IF (NDIM.LT.NPT2) GO TO 100
      NDMQ=NPT3
      IF (NDIM.LT.NPT4) NDMQ=NDIM
      DO 40 K=NPT2,NDMQ,2
      US=SQRT(GAMMA*PELECT(K)/DELECT(K))
      XM=UELECT(K)/US
      ADM=ADMSE(K)/XMSE
      DNS1=DELECT(K)/XMSE
      WRITE(iUnitOutput,1022) K,ALTD(K),UELECT(K),XM,DNS1,PELECT(K),TELECT(K),ADM
40    CONTINUE
      IF (NDIM.LT.NPT4) GO TO 100
      NDMQ=NPT5
      IF (NDIM.LT.NPT6) NDMQ=NDIM
      DO 50 K=NPT4,NDMQ,5
      US=SQRT(GAMMA*PELECT(K)/DELECT(K))
      XM=UELECT(K)/US
      ADM=ADMSE(K)/XMSE
      DNS1=DELECT(K)/XMSE
      WRITE(iUnitOutput,1022) K,ALTD(K),UELECT(K),XM,DNS1,PELECT(K),TELECT(K),ADM
50    CONTINUE
      IF (NDIM.LT.NPT6) GO TO 100
      DO 60 K=NPT6,NDIM,10
      US=SQRT(GAMMA*PELECT(K)/DELECT(K))
      XM=UELECT(K)/US
      ADM=ADMSE(K)/XMSE
      DNS1=DELECT(K)/XMSE
      WRITE(iUnitOutput,1022) K,ALTD(K),UELECT(K),XM,DNS1,PELECT(K),TELECT(K),ADM
60    CONTINUE
100   CONTINUE
      K=NDIM1
      XM=UBGNDE/WBGNDE
      DNS1=DBGNDE/XMSE
      WRITE(iUnitOutput,1012) K,ALTMAX,UBGNDE,XM,DNS1,PBGNDE,TBGNDE
      RETURN
      END
      SUBROUTINE PRNTEF
      use ModCommonVariables
C
C
C
      WRITE(iUnitOutput,1010) TIME,DT,NSTEP
1010  FORMAT(1H1,10X,'TIME=',1PE12.4,'SEC',10X,'TIME STEP=',1PE12.4,
     ;'SEC',10X,'NSTEP=',I6)
      WRITE(iUnitOutput,1013)
1013  FORMAT(1H0,40X,'NEW ELECTRIC FIELD AND SOURCE PARAMETERS')
      WRITE(iUnitOutput,1011)
1011  FORMAT(13X,'ALT',6X,'EFIELD',6X,'FCLSNO',6X,'ECLSNO',6X,'FCLSHE',
     ;6X,'ECLSHE',6X,'FCLSNH',6X,'ECLSNH',6X,'FCLSNE',6X,'ECLSNE')
      NDMQ=NPT1
      IF (NDIM.LT.NPT2) NDMQ=NDIM
      DO 30 K=1,NDMQ
      WRITE(iUnitOutput,1012) K,ALTD(K),EFIELD(K),FCLSNO(K),ECLSNO(K),FCLSHE(K),
     ;ECLSHE(K),FCLSNH(K),ECLSNH(K),FCLSNE(K),ECLSNE(K)
30    CONTINUE
      IF (NDIM.LT.NPT2) GO TO 100
      NDMQ=NPT3
      IF (NDIM.LT.NPT4) NDMQ=NDIM
      DO 40 K=NPT2,NDMQ,2
      WRITE(iUnitOutput,1012) K,ALTD(K),EFIELD(K),FCLSNO(K),ECLSNO(K),FCLSHE(K),
     ;ECLSHE(K),FCLSNH(K),ECLSNH(K),FCLSNE(K),ECLSNE(K)
40    CONTINUE
      IF (NDIM.LT.NPT4) GO TO 100
      NDMQ=NPT5
      IF (NDIM.LT.NPT6) NDMQ=NDIM
      DO 50 K=NPT4,NDMQ,5
      WRITE(iUnitOutput,1012) K,ALTD(K),EFIELD(K),FCLSNO(K),ECLSNO(K),FCLSHE(K),
     ;ECLSHE(K),FCLSNH(K),ECLSNH(K),FCLSNE(K),ECLSNE(K)
50    CONTINUE
      IF (NDIM.LT.NPT6) GO TO 100
      DO 60 K=NPT6,NDIM,10
      WRITE(iUnitOutput,1012) K,ALTD(K),EFIELD(K),FCLSNO(K),ECLSNO(K),FCLSHE(K),
     ;ECLSHE(K),FCLSNH(K),ECLSNH(K),FCLSNE(K),ECLSNE(K)
60    CONTINUE
100   CONTINUE
1012  FORMAT(3X,I3,0PF11.2,2X,9(1PE13.4E3))
      RETURN
      END
