      SUBROUTINE PRNTEL
      use ModCommonVariables
C
C
C
      WRITE(16,1010) TIME,DT,NSTEP
1010  FORMAT(1H1,10X,'TIME=',1PE12.4,'SEC',10X,'TIME STEP=',1PE12.4,
     ;'SEC',10X,'NSTEP=',I6)
      WRITE(16,1013)
1013  FORMAT(1H0,47X,'NEW ELECTRON PARAMETERS')
      WRITE(16,1011)
1011  FORMAT(16X,'ALT',10X,'VELOCITY',8X,'MACH NO',9X,'DENSITY',9X,
     ;'PRESSURE',6X,'TEMPERATURE',5X,' NET SOURCE'/)
      K=0
      XM=USURFE/WSURFE
      DNS1=DSURFE/XMSE
      WRITE(16,1012) K,ALTMIN,USURFE,XM,DNS1,PSURFE,TSURFE
1012  FORMAT(3X,I3,0PF14.2,2X,5(1PE16.5))
      NDMQ=NPT1
      IF (NDIM.LT.NPT2) NDMQ=NDIM
      DO 30 K=1,NDMQ
      US=SQRT(GAMMA*PELECT(K)/DELECT(K))
      XM=UELECT(K)/US
      ADM=ADMSE(K)/XMSE
      DNS1=DELECT(K)/XMSE
      WRITE(16,1022) K,ALTD(K),UELECT(K),XM,DNS1,PELECT(K),TELECT(K),ADM
1022  FORMAT(3X,I3,0PF14.2,2X,6(1PE16.5))
30    CONTINUE
      IF (NDIM.LT.NPT2) GO TO 100
      NDMQ=NPT3
      IF (NDIM.LT.NPT4) NDMQ=NDIM
      DO 40 K=NPT2,NDMQ,2
      US=SQRT(GAMMA*PELECT(K)/DELECT(K))
      XM=UELECT(K)/US
      ADM=ADMSE(K)/XMSE
      DNS1=DELECT(K)/XMSE
      WRITE(16,1022) K,ALTD(K),UELECT(K),XM,DNS1,PELECT(K),TELECT(K),ADM
40    CONTINUE
      IF (NDIM.LT.NPT4) GO TO 100
      NDMQ=NPT5
      IF (NDIM.LT.NPT6) NDMQ=NDIM
      DO 50 K=NPT4,NDMQ,5
      US=SQRT(GAMMA*PELECT(K)/DELECT(K))
      XM=UELECT(K)/US
      ADM=ADMSE(K)/XMSE
      DNS1=DELECT(K)/XMSE
      WRITE(16,1022) K,ALTD(K),UELECT(K),XM,DNS1,PELECT(K),TELECT(K),ADM
50    CONTINUE
      IF (NDIM.LT.NPT6) GO TO 100
      DO 60 K=NPT6,NDIM,10
      US=SQRT(GAMMA*PELECT(K)/DELECT(K))
      XM=UELECT(K)/US
      ADM=ADMSE(K)/XMSE
      DNS1=DELECT(K)/XMSE
      WRITE(16,1022) K,ALTD(K),UELECT(K),XM,DNS1,PELECT(K),TELECT(K),ADM
60    CONTINUE
100   CONTINUE
      K=NDIM1
      XM=UBGNDE/WBGNDE
      DNS1=DBGNDE/XMSE
      WRITE(16,1012) K,ALTMAX,UBGNDE,XM,DNS1,PBGNDE,TBGNDE
      RETURN
      END
